### ISSUE TITLE
GitHub Release support

### ISSUE THREAD

**Issue by rjmholt** [microsoft/PowerShellForGitHub#110]
I wrote some PowerShell to publish a GitHub release recently ([here](https://github.com/PowerShell/vscode-powershell/blob/a7401961967f50f0de0dc64a82718b1ceb9d8ec5/tools/GitHubTools.psm1#L232-L328)) and was wondering if you would like it? It needs changing to work with the conventions of this module, of course, but with some guidance I can do that.

Let me know if you're interested. I haven't exposed any other GitHub Release API support, but could relatively easily.

**Comment by HowardWolosky** [comment]
Go for it.  Would love to have it.
It also might be worthwhile to see if [vscode-powershell](https://github.com/PowerShell/vscode-powershell) could depend on this module for the GitHub integration functionality, as opposed to maintaining two implementations trying to do the same thing, one more generally than the other...

**Comment by rjmholt** [comment]
> It also might be worthwhile to see if vscode-powershell could depend on this module for the GitHub integration functionality, as opposed to maintaining two implementations trying to do the same thing, one more generally than the other...

Yes that's my thinking too
