### ISSUE TITLE
Progress is Incorrectly Displayed

### ISSUE THREAD

**Issue by StartAutomating** [microsoft/PowerShellForGitHub#119]
The helper function Wait-JobWithAnimation incorrectly handles progress, and this makes it look quite ugly indeed in the ISE (a spew of non-wrapped yellow lines).

The root of the problem is that you are creating your own Write-Progress.  Please use Write-Progress instead, as this is more standard and will be honored across more PowerShell hosts.

The issue reproduces everywhere, but is worst in the PowerShell ISE.
PowerShellForGitHub version: 0.8.0
$psVersionTable
Name                           Value                                                                                          
----                           -----                                                                                          
PSVersion                      5.1.17763.503                                                                                  
PSEdition                      Desktop                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                        
BuildVersion                   10.0.17763.503                                                                                 
CLRVersion                     4.0.30319.42000                                                                                
WSManStackVersion              3.0                                                                                            
PSRemotingProtocolVersion      2.3                                                                                            
SerializationVersion           1.1.0.1                                                                                        

----

To detail the fix:
Create an ID before the while loop (Line 57)

Change your Write-InteractiveHost to Write-Progress (line 94)
        Write-Progress "$($animationFrames[$($iteration % $($animationFrames.Length))])" "Elapsed: $([int]($iteration / $framesPerSecond)) second(s)" -PercentComplete $((($iteration % $($animationFrames.Length)) / $animationFrames.Length) * 100) -id $id

Complete the Progress message at the end (lines 101 & 108)

Get rid of your Write-InteractiveHost at the very end

**Comment by HowardWolosky** [comment]
Interesting. Thanks for the report! Want to submit a PR with this suggested change for me to check out?  It's also possible to use `-NoStatus` to avoid seeing any of that progress being reported out.
