### ISSUE TITLE
Optimizations for array creation

### ISSUE THREAD

**Issue by PrzemyslawKlys** [microsoft/PowerShellForGitHub#121]
Not really an issue, but with larger arrays things start to be less than optimal for performance when using an approach as seen here:

https://github.com/microsoft/PowerShellForGitHub/blob/220333a71214fb88a33093b5e907d431dcfdb4c8/GitHubRepositories.ps1#L442-L450

It can be optimized like that;

```PowerShell
    $getParams = @(
        if ($PSBoundParameters.ContainsKey('Visibility')) { "visibility=$($Visibility.ToLower())" }
        if ($PSBoundParameters.ContainsKey('Sort')) { "sort=$($sortConverter[$Sort])" }
        if ($PSBoundParameters.ContainsKey('Type')) { "type=$($Type.ToLower())" }
        if ($PSBoundParameters.ContainsKey('Direction')) { "direction=$($directionConverter[$Direction])" }
        if ($PSBoundParameters.ContainsKey('Affiliation') -and $Affiliation.Count -gt 0) {
            "affiliation=$($Affiliation -join ',')"
        }
    )
```

Not sure if there's a need for that. I can see it being built the same way all over the code, but the amount of elements probably is too small to notice a performance difference.

**Comment by HowardWolosky** [comment]
I haven't done true measurements on what's currently there vs your suggestion, but historically there is negligible impact to doing array manipulation the way it's currently being performed in the module at the scale that it's currently used (<10 operations).  In theory, I could also switch to an `[ArrayList]' which would be more efficient with it's `.Add()` operator, but again, at the scale that it's used here, I think that attempts at optimizing this part of the code would have a negligible impact relative to the time and effort to implement, review and test, as well as the (subjectively) added complexity it would add to the code.

As such, short of any real performance numbers showing that I'm wrong, I don't see any value in spending time on this area of the code.

I greatly appreciate you taking a look into this though, and would definitely encourage your participation  in other parts of the project.

Thanks for the report.

**Comment by PrzemyslawKlys** [comment]
Actually using ArrayList is discouraged per Microsoft Recommendation.

I've written a blog post about it: https://evotec.xyz/powershell-few-tricks-about-hashtable-and-array-i-wish-i-knew-when-i-started/ 

![image](https://user-images.githubusercontent.com/15063294/61107251-c7b76e80-a47f-11e9-94e7-19b2d81de439.png)

And according to my own tests (also from those in the article) using Array the way I've shown is faster than both GenericList and Arraylist (if the use is possible - sometimes you need to add stuff to two different arrays within one loop). 

Of course, for this case, it doesn't matter because the array size is just too small but thought I would mention this. If I will ever find anything that needs fixing/help with your project I'll jump in :)
