### ISSUE TITLE
Watchers_Count, Watchers returning wrong value

### ISSUE THREAD

**Issue by PrzemyslawKlys** [microsoft/PowerShellForGitHub#122]
Here's an output of my query:

```powershell
$T = Get-GitHubRepository -OwnerName EvotecIT
$T | Sort-Object Stargazers_Count -Descending | Format-Table full_name, Name, Stargazers_Count, Watchers_Count, Watchers,forks_count, Open_issues,license, Language, HTML_URL, Fork, Created_At, Updated_At, Pushed_At, Archived -AutoSize
```

![image](https://user-images.githubusercontent.com/15063294/60774294-8e46d200-a112-11e9-8a58-50a2f3edd409.png)

It seems watchers_count, watchers are the same as stargazers_count which isn't really true.

**Comment by HowardWolosky** [comment]
Yeah, I've noticed that too. It's a bug with the API though as far as I can tell... I've been meaning to open a bug against the API for that issue...

**Comment by HowardWolosky** [comment]
There doesn't appear to be anything that can be done about this as per their [blog post](https://developer.github.com/changes/2012-09-05-watcher-api/) and this [forum response](https://github.community/t5/GitHub-API-Development-and/API-is-very-confusing-by-listing-Stars-count-for-Watchers-count/m-p/19971).

**Comment by PrzemyslawKlys** [comment]
Ok, so there should be subscribers count I can use for Watchers. Thank you

**Comment by gabrielmongefranco** [comment]
Hello, I am not seeing a "subscribers_count" anywhere, which is the correct way of getting "watchers." 
See: https://docs.github.com/en/rest/activity/watching?apiVersion=2022-11-28

**Comment by HowardWolosky** [comment]
> Hello, I am not seeing a "subscribers_count" anywhere, which is the correct way of getting "watchers." See: https://docs.github.com/en/rest/activity/watching?apiVersion=2022-11-28

The documentation appears to be out-of-date.  It looks like the way you could achieve this right now is:

```powershell
$response = Invoke-GHRestMethod -UriFragment 'repos/microsoft/PowerShellForGitHub/subscribers' -Method Get
$subscriber_count = $response.Count                   # or $watcher_count, if you prefer
```

The module doesn't currently have a direct API for calling that end-point, but you can call it today for the time-being with `Invoke-GHRestMethod`.  Does this help?

**Comment by gabrielmongefranco** [comment]
Yep, that's actually what I ended up doing. :) Thanks!!
