### ISSUE TITLE
Bug in Update-GitHubRepository Archived parameter usage

### ISSUE THREAD

**Issue by amis92** [microsoft/PowerShellForGitHub#134]
So I'm pretty sure there's a bug in `Update-GitHubRepository` cmdlet - found it by just browsing source code:

https://github.com/microsoft/PowerShellForGitHub/blob/013452b5cd8a7d7655cb32031d5ebdb580af16d9/GitHubRepositories.ps1#L613

Passing the `Archived` switch will result in `archived=false` parameter passed to API.

Is:
`$hashBody['archived'] = (-not $Archived.ToBool())`
Should be:
`$hashBody['archived'] = $Archived.ToBool()`

This is probably a copy-paste error since all other properties use inverted style:

https://github.com/microsoft/PowerShellForGitHub/blob/013452b5cd8a7d7655cb32031d5ebdb580af16d9/GitHubRepositories.ps1#L610-L614

**Comment by HowardWolosky** [comment]
Wow....great catch @amis92!  Thanks so much for pointing that out and opening the Issue to let us know.  What inspired you to do code inspection like this?

**Comment by amis92** [comment]
Well I'm writing an automation script and whenever I can I check the code I depend on, but also I guess a lucky catch. :)
