### ISSUE TITLE
Enhance UT's for GitHubRepositories.ps1

### ISSUE THREAD

**Issue by HowardWolosky** [microsoft/PowerShellForGitHub#139]
We use a number of the functions within this file throughout the other UT's, but not all of them.  There is a lack of comprehensive testing available for all the methods within this file as was recently demonstrated with #134 and #136 (around `Update-GitHubRepository`).

We should close the gaps on the testing of the functions within this file to increase code coverage and reduce regression possibilities.

**Comment by themilanfan** [comment]
I'll have a go at this
