### ISSUE TITLE
Suggestion: Add ability to rename a repository; Rename-GitHubRepository?

### ISSUE THREAD

**Issue by mtboren** [microsoft/PowerShellForGitHub#144]
Firstly, great module.

One minor capability that we can add:  the ability to rename a repository.  While this may not be an everyday activity, there are times when it is a need.

Some answers to the [Contributing Suggestions](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#suggestions) items:

- _What you want to achieve / what is the problem that you want to address_:
    Add the ability to rename a GitHub repository. This may be through a new cmdlet like `Rename-GitHubRepository`, or via a new parameter to the existing `Update-GitHubRepository` cmdlet

- _What is your approach for solving the problem_:
    Until such a time that this module directly supports repo renames, we can use the `Invoke-GHRestMethod` cmdlet from the module to rename a repository.  See the Gist at [mtboren/snippets_RenameGitHubRepository.ps1](https://gist.github.com/mtboren/4d68fe0aca90d89bdbd4526b24a22a8b)
- _A user scenario of the feature / enhancement in action_:
    Let's say that Billy forked repoX, and Billy likes to improve clarity about repos -- he adds the prefix `fork_` to the repos that he forks, using the name as an additional indicator/clarifier.  So, much like `Rename-Item` for a filesystem object, he would expect to solve this need by doing something like:
    ```PowerShell
    New-GitHubRepositoryFork -Uri https://github.com/aws-quickstart/quickstart-dotnet-serverless-cicd | Rename-GitHubRepository -NewName billyfork_quickstart-dotnet-serverless-cicd
    ```

Looking forward to using this module more

**Comment by mtboren** [comment]
..I would add the `Suggestion` label to this Issue, but I seem to not have sufficient permission to do so.  I'm sure that the right person will add said label.

**Comment by HowardWolosky** [comment]
Your suggestion seems reasonable. Want to take a crack at adding that command yourself?

**Comment by mtboren** [comment]
Thx, @HowardWolosky .  And, surre!  I'll plan to do just that.

**Comment by mtboren** [comment]
Created PR #145 -- hurray!
