### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by jpomfret** [microsoft/PowerShellForGitHub#158]

**Comment by jpomfret** [comment]
Sorry @HowardWolosky! I thought I'd cancelled quick enough, and I didn't check. Thanks for closing.

Looking at projects right now - hopefully I'll contribute something a little more useful to you :D

**Comment by HowardWolosky** [comment]
No worries, @jpomfret.  I'm surprised it hasn't happened more often, given that's the primary example for `New-GitHubIssue`.   Looking forward to seeing a contribution from you!
