### ISSUE TITLE
Remove- commands should prompt for confirmation 

### ISSUE THREAD

**Issue by jpomfret** [microsoft/PowerShellForGitHub#171]
Functions that remove something should have ConfirmImpact set to High.

I noticed that `Remove-GitHubRepository` doesn't prompt for confirmation, these are also missing that:
- Remove-GithubAssignee
- Remove-GitHubComment
- Remove-GitHubIssueLabel
- Remove-GitHubLabel
- Remove-GitHubMilestone
- Remove-GitHubRepository

**Comment by HowardWolosky** [comment]
Indeed.  And similar to the [cl](https://github.com/microsoft/PowerShellForGitHub/commit/536b762425d51a181166c2c47ad2b00014911d1d) that introduced this concept, there should also be an example added that shows how to avoid the prompting as well.

https://github.com/microsoft/PowerShellForGitHub/blob/536b762425d51a181166c2c47ad2b00014911d1d/GitHubRepositories.ps1#L503-L505
