### ISSUE TITLE
Figure out why Linux and macOS get different hashes

### ISSUE THREAD

**Issue by HowardWolosky** [microsoft/PowerShellForGitHub#182]
For some reason, calling `Get-SHA512Hash` from `Helpers.ps1` is returning back different results on macOS and Linux vs Windows.  Had to [disable](https://github.com/microsoft/PowerShellForGitHub/blob/93689d69eedc50f084982a6fba21183857507dbb/build/pipelines/azure-pipelines.ci.yaml#L33-L35) the [`./templates/verify-testConfigSettingsHash.yaml`](https://github.com/microsoft/PowerShellForGitHub/blob/93689d69eedc50f084982a6fba21183857507dbb/build/pipelines/templates/verify-testConfigSettingsHash.yaml) check on those OS's as part of #181 until that can be better understood.

This means that [the check in Tests\Common.ps1](https://github.com/microsoft/PowerShellForGitHub/blob/93689d69eedc50f084982a6fba21183857507dbb/Tests/Common.ps1#L51-L60) that verifies you've modified the test settings configuration may not be working correctly on those platforms.

**Comment by X-Guardian** [comment]
Hi @HowardWolosky, you are hitting the age old Windows/Linux `crlf` vs `lf` issue on the `Setttings.ps1` file. If you force the file to be checked out by Git with `crlf` eol markers using a `.gitattributes` file, you will get consistent sha values. More details here: [Configuring Git to Handle Line Endings](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings).

I've tested this on the [CITest](https://github.com/X-Guardian/PowerShellForGitHub/tree/CITest) branch of my forked copy of the repo.

Here is the [Azure Pipelines Run](https://dev.azure.com/simonheather99/PowerShellForGitHub/_build/results?buildId=74&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3) showing `verify-testConfigSettingsHash` running successfully on Windows, Ubuntu and MacOS.

**Comment by HowardWolosky** [comment]
@X-Guardian - Thank you so very much!  What a completely thorough response and solution.  I've added that fix to my PR for trying to completely fix the CI build (#183).  The only thing blocking that PR now is determining why there are 7 tests that fail in CI build not locally.
