### ISSUE TITLE
New/Update-GitHubRepository: Add Support for delete_branch_on_merge API Property

### ISSUE THREAD

**Issue by X-Guardian** [microsoft/PowerShellForGitHub#189]
### Description

The GitHub [Create](https://developer.github.com/v3/repos/#create-a-repository-for-the-authenticated-user)/[Update](https://developer.github.com/v3/repos/#update-a-repository) Repository APIs have a `delete_branch_on_merge` property which is not currently supported by the `New-GitHubRepository` and `Update-GitHubRepository` functions. This allows automatically deleting of head branches when pull requests are merged within the repo.

### Proposal

Add a `DeleteBranchOnMerge` switch parameter to both functions to add support for this feature.

### API Detail

```
delete_branch_on_merge | boolean | Either `true` to allow automatically deleting head branches when pull requests are merged, or `false` to prevent automatic deletion. Default: `false`.
```

**Comment by HowardWolosky** [comment]
Makes sense to me.  We should also make sure that there aren't any other options that the functions are missing, for completness.

**Comment by X-Guardian** [comment]
Looking at the GitHub [Repositories](https://developer.github.com/v3/repos/) REST API Docs, the Create/Update APIs also have the `visibility` and `is_template` parameters which are not currently supported by the `GitHubRepository` functions.

#### API Detail

Parameter | Type | Description
-|-|-
visibility | string | Can be `public` or `private`. If your organization is associated with an enterprise account using GitHub Enterprise Cloud or GitHub Enterprise Server 2.20+, `visibility` can also be `internal`. For more information, see "[Creating an internal repository](https://help.github.com/github/creating-cloning-and-archiving-repositories/creating-an-internal-repository)" in the GitHub Help documentation. The `visibility` parameter overrides the `private` parameter when you use both parameters with the `nebula-preview` preview header.
is_template | boolean | Either `true` to make this repo available as a template repository or `false` to prevent it. Default: `false`.
