### ISSUE TITLE
Suggestion: Add 'Set-GitHubConfiguration -DefaultNoStatus' to All Pester Tests

### ISSUE THREAD

**Issue by X-Guardian** [microsoft/PowerShellForGitHub#206]
Currently the full suite of Pester tests take between 20 to 25 minutes to run per environment within the CI pipeline. There are currently three environments being tested (Windows, Linux and MacOS) meaning the full CI takes about 1 hour 15 mins to run.

Locally running the `GitHubRepositories.tests` Pester tests and adding `Set-GitHubConfiguration -DefaultNoStatus` in a `BeforeAll` block for each `Describe` block, reduces the time for the `GitHubRepositories` tests to run from approx 60 secs to 25 secs.

Extrapolating this up, applying this change to all tests may reduce the full test suite run from 1 hour 15 mins to approx 30 mins.

I've also noticed that the Azure DevOps Pipeline raw log for the 'Run Unit Tests via Pester` step are 'corrupted' by the status output on [Linux](https://dev.azure.com/ms/341bcd7d-fac3-430a-a077-9c95d49a8ba5/_apis/build/builds/84257/logs/23) and [MacOS](https://dev.azure.com/ms/341bcd7d-fac3-430a-a077-9c95d49a8ba5/_apis/build/builds/84257/logs/35), unlike on [Windows](https://dev.azure.com/ms/341bcd7d-fac3-430a-a077-9c95d49a8ba5/_apis/build/builds/84257/logs/10). Making this change would also resolve this.

**Comment by HowardWolosky** [comment]
Thanks @X-Guardian! -- I had noticed the "corruption" in the raw output log for Linux, but had been unaware of the _time_ impact. Nice call out.  I'll put out a PR now to see what impact that practically makes.  If it's even remotely close to being that impactful, it's definitely worth it to make the change.
