### ISSUE TITLE
Suggestion: Add PowerShell Help Based Wiki Documentation

### ISSUE THREAD

**Issue by X-Guardian** [microsoft/PowerShellForGitHub#208]
There is currently no on-line documentation for the `PowerShellForGitHub cmdlets`. This can easily be built from the PowerShell help system using the [PlaytPS](https://github.com/PowerShell/platyps) PowerShell module and published to the GitHub Wiki.

For an example, I have published this to the [Wiki](https://github.com/X-Guardian/PowerShellForGitHub/wiki) of my PowerShellForGitHub fork.

**Comment by HowardWolosky** [comment]
Seems like a pretty great idea, and a good use of the Wiki which currently isn't getting used at all.

How did you automate the deployment of the documentation to the GitHub Wiki?  I'd probably want to write an additional step in the [release template](https://github.com/microsoft/PowerShellForGitHub/blob/master/build/pipelines/templates/prepare-release-internalOnly.yaml) to ensure that happens automatically with each release.

**Comment by X-Guardian** [comment]
The Wiki is just another GitHub repo (https://github.com/microsoft/PowerShellForGitHub.wiki), so you can script the clone, update, commit and push process. You need to add an initial page via the web interface to initialize it.

I need to tweak my script which runs PlatyPS, as I currently need to do some manual changes to get the markdown working with the GitHub Wiki. I'll let you know when it is ready.

**Comment by X-Guardian** [comment]
OK, the base script to auto-generate the Wiki pages is here: [Build-Wiki.ps1](https://github.com/X-Guardian/PowerShellForGitHub/wiki/Build-Wiki.ps1). 

Sample code to run Git can be found in the `Publish-WikiContent` function in the [DSCResource WikiPages](https://github.com/PowerShell/DscResource.Tests/blob/dev/DscResource.DocumentationHelper/WikiPages.psm1) module. It was written for AppVeyor, but would just need some minor changes to run on Azure Pipelines.

**Comment by HowardWolosky** [comment]
@X-Guardian - I completely missed that you had posted that previous comment at the time (which is frustrating given that you had posted it the same day as the previous one that I had 👍 ).  Your `Build-Wiki.ps1` script is gone now that you had to rebuild your fork.  I think you haven't _lost it_ though...you probably just need to re-publish your wiki sub-repo?  I'm interested in taking a look to see how hard this might be to hook up this weekend...

**Comment by X-Guardian** [comment]
Hi @HowardWolosky, I've restored the Wiki into my fork.
