### ISSUE TITLE
Copy-paste bug: Set-GitHubContent parameter checks on invalid variables

### ISSUE THREAD

**Issue by amis92** [microsoft/PowerShellForGitHub#285]
#### Issue Details

Browsing through source code, I found this:

https://github.com/microsoft/PowerShellForGitHub/blob/5b835cd5437d7d9d58217034900c3400f617f5c1/GitHubContents.ps1#L392-L396

Looking at a similar block above, I'm pretty sure it's a copy-paste error: `IsNullOrEmpty` checks should be called on `AuthorXxx` and not `CommiterXxx` variables.

#### Suggested solution to the issue
`IsNullOrEmpty` checks should be called on `AuthorXxx` and not `CommiterXxx` variables.

#### Requested Assignment
- I'm just reporting this problem, but don't want to fix it.

#### Module Version
0.15.1 (master as of writing date)

**Comment by HowardWolosky** [comment]
Thanks for catching this, @amis92.  It's odd, we do have UT's around this, but it appears that they need some improvement (like having different values between `$authorName/$authorEmail` and `$committerName/$committerEmail`)

https://github.com/microsoft/PowerShellForGitHub/blob/5b835cd5437d7d9d58217034900c3400f617f5c1/Tests/GitHubContents.tests.ps1#L271-L274

This is a pretty easy fix for someone in the community that has been interested in contributing but hasn't known where to start. I'll leave this up for grabs for a couple days to see if someone would like to fix it before I take it on myself.
