### ISSUE TITLE
Get-GitHubOrganizationMembers not working

### ISSUE THREAD

**Issue by jaxxstar** [microsoft/PowerShellForGitHub#287]
#### Issue Details
Get-GitHubOrganizationMembers not working

#### Steps to reproduce the issue
```powershell
   $organizationMembers = Get-GitHubOrganizationMembers -OrganizationName 'spider-tronix'
```

#### Verbose logs showing the problem
Get-GitHubOrganizationMembers : The term 'Get-GitHubOrganizationMembers' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again.
At line:1 char:24
+ $organizationMembers = Get-GitHubOrganizationMembers -OrganizationNam ...
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-GitHubOrganizationMembers:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

#### Requested Assignment

    - If possible, I would like to fix this.

#### Operating System
OsName               : Microsoft Windows 10 Home
OsOperatingSystemSKU : WindowsHome
OsArchitecture       : 64-bit
WindowsVersion       : 1903
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### PowerShell Version
Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Module Version
Running: 0.15.1
Installed: 0.15.1

**Comment by HowardWolosky** [comment]
Good catch.
Looks like a documentation bug.

https://github.com/microsoft/PowerShellForGitHub/blob/5b835cd5437d7d9d58217034900c3400f617f5c1/USAGE.md#L425-426

Those functions should be singular, nor plural.

```powershell
$organizationMembers = Get-GitHubOrganizationMember -OrganizationName 'OrganizationName'
$teamMembers = Get-GitHubTeamMember -OrganizationName 'OrganizationName' -TeamName 'TeamName'
```
Easy fix if you want to make it.
