### ISSUE TITLE
How to get the number of branch commits for a individual repository?

### ISSUE THREAD

**Issue by HowardWolosky** [microsoft/PowerShellForGitHub#289]
_Opening this on behalf of @jaxxstar who asked this question in a different channel_

#### A description of your problem or question

This is the original message from @jaxxstar:
>I have created a repository for a github organization which is able to measure the weekly commits done by members of the org, I'm using the powershellforgithub module, but the only problem that I'm facing is that I'm not able to get the number of branch commits for a individual repository.

#### Steps to reproduce the issue
```powershell
   # Include your repro steps here
```

**Comment by HowardWolosky** [comment]
@jaxxstar - Please add more details if this response doesn't answer your question....

At the moment, the API that you need to call hasn't been implemented into the module.  You're welcome to implement it and submit a pull request.  The API that you need to use is [this one](https://developer.github.com/v3/repos/commits/#list-commits).

In the absence of using the implemented API, you can use `Invoke-GHRestMethod` or `Invoke-GHRestMethodMultipleResult` to call the API directly.  Something like this:

```powershell
   $ownerName = "<yourOwnerName>"
   $repositoryName = "<yourRepositoryName>"
   $sha = "<branchName>"
    $params = @{
        'UriFragment' = "repos/$ownerName/$repositoryName/commits"
        'Description' = "Getting commits for $repositoryName"
    }

$commits = Invoke-GHRestMethodMultipleResult @params
```

**Comment by jaxxstar** [comment]
@HowardWolosky : The response answered my queries about getting the branch commits. I would like to implement the API into the module and I'm working on it. The Invoke-GHRestMethod which you suggested earlier gets the commits along with the details, I was checking if there is any other way to get the branch name also through the API instead of entering it manually.

**Comment by HowardWolosky** [comment]
> I was checking if there is any other way to get the branch name also through the API instead of entering it manually.

You can call `Get-GitHubBranch` to get all of the branches for a repository.  Since you [need to support the pipeline](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#pipeline-support) with your change, you'll then be able to just pipe a `GitHub.Branch` response directly into your new function in order to get the related commits.

**Comment by jaxxstar** [comment]
@HowardWolosky is there any documentation for the Github.Branch response?

**Comment by HowardWolosky** [comment]
> @HowardWolosky Howard Wolosky FTE is there any documentation for the Github.Branch response?

There's documentation for every response via the [GitHub API documentation](https://developer.github.com/v3/repos/branches/#get-a-branch).
