### ISSUE TITLE
Get-GitHubTeam ID

### ISSUE THREAD

**Issue by ndouek-qontigo** [microsoft/PowerShellForGitHub#291]
#20 ## Issue Details
This does not return the ID
Get-GitHubTeam -OrganizationName {name} -TeamName {name}

However.... execute these together and the team ID is returned on the second 
Get-GitHubTeam -OrganizationName {name}
Get-GitHubTeam -OrganizationName {name} -TeamName {name}

#### Steps to reproduce the issue
```powershell
   # Include your repro steps here
```

#### PowerShell Version
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

#### Module Version
Running: 0.15.1
Installed: 0.15.1

**Comment by HowardWolosky** [comment]
The behavior you are describing is as expected, as that is how the API itself is designed.
If you look at the documentation for the function (`Get-Help -ShowWindow`), you'll see that it returns back two different types of results: `GitHub.Team` and `GitHub.TeamSummary`.  That mirrors what the API itself will return back.

API: [List all teams](https://developer.github.com/v3/teams/#list-teams)
API: [Get specific team](https://developer.github.com/v3/teams/#get-a-team-by-name)

In general, the API returns less information per record when returning a number of records vs when it's getting a specific record.
