### ISSUE TITLE
New-GitHubRepository results in Request forbidden by administrative rules.

### ISSUE THREAD

**Issue by alfred-madl** [microsoft/PowerShellForGitHub#296]
Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.

**Comment by HowardWolosky** [comment]
Were you trying to make a new repo in an organization or on your personal account?

**Comment by alfred-madl** [comment]
Personal account…Authentication token is set…

Alfred

**Comment by HowardWolosky** [comment]
When you created the issue, there was a template to fill out with some requested information in order to narrow down potential issues.  Can you please update your initial post with that requested detail?

**Comment by alfred-madl** [comment]
#### Steps to reproduce the issue
PS /Users/alfredmadl> New-GitHubRepository

cmdlet New-GitHubRepository at command pipeline position 1
Supply values for the following parameters:
RepositoryName: xxxxx
Telemetry is currently enabled.  It can be disabled by calling "Set-GitHubConfiguration -DisableTelemetry". Refer to USAGE.md#telemetry for more information. Stop seeing this message in the future by calling "Set-GitHubConfiguration -SuppressTelemetryReminder".
Invoke-WebRequest: /usr/local/share/powershell/Modules/PowerShellForGitHub/0.15.1/GitHubCore.ps1:294
Line |
 294 |          $result = Invoke-WebRequest @params
     |                    ~~~~~~~~~~~~~~~~~~~~~~~~~
     |  Request forbidden by administrative rules. Please make sure your request has a User-Agent header
     | (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.

PS /Users/alfredmadl> 

#### Verbose logs showing the problem

PS /Users/alfredmadl> New-GitHubRepository -Verbose

cmdlet New-GitHubRepository at command pipeline position 1
Supply values for the following parameters:
RepositoryName: xxxxx
VERBOSE: [0.15.1] Executing: New-GitHubRepository -Verbose:$true -RepositoryName "xxxxx"
VERBOSE: Performing the operation "Create GitHub Repository" on target "xxxxx".
VERBOSE: Creating xxxxx
VERBOSE: Accessing [Post] https://api.github.com/user/repos [Timeout = 0)]
VERBOSE: Request includes a body.
VERBOSE: POST https://api.github.com/user/repos with 21-byte payload
VERBOSE: received -byte response of content type text/html
VERBOSE: [0.15.1] Executing: Set-TelemetryException -ErrorBucket "New-GitHubRepository"
VERBOSE: Sending telemetry event data to https://dc.services.visualstudio.com/v2/track [Timeout = 0)]
VERBOSE: POST https://dc.services.visualstudio.com/v2/track with 1298-byte payload
VERBOSE: received 49-byte response of content type application/json
Invoke-WebRequest: /usr/local/share/powershell/Modules/PowerShellForGitHub/0.15.1/GitHubCore.ps1:294
Line |
 294 |          $result = Invoke-WebRequest @params
     |                    ~~~~~~~~~~~~~~~~~~~~~~~~~
     |  Request forbidden by administrative rules. Please make sure your request has a User-Agent header
     | (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.

PS /Users/alfredmadl> 

#### Operating System

Name                           Value
----                           -----
OSVersion                      Unix 19.6.0.0
Is 64-bit                      True
Current culture                
Current UI culture    

macOS Catalina 10.15.7

#### PowerShell Version

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEA…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

#### Module Version

Running: 0.15.1
Installed: 0.15.1

**Comment by HowardWolosky** [comment]
Interesting.

> | ~~~~~~~~~~~~~~~~~~~~~~~~~
> | Request forbidden by administrative rules. Please make sure your request has a User-Agent header
> | (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.

We do set the `user-agent`: 
https://github.com/microsoft/PowerShellForGitHub/blob/ec7950c02c1e52af2a6edc30331982d172f6e7ff/GitHubCore.ps1#L225-L228

The [most recent CI run from 10/17/2020](https://dev.azure.com/ms/PowerShellForGitHub/_build/results?buildId=116447&view=results) also passed successfully [for macOS](https://dev.azure.com/ms/PowerShellForGitHub/_build/results?buildId=116447&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7) which runs `macOS-latest` which [currently maps to `10.15`](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml), and that uses the latest PowerShell Core which is currently `7.0.3`.  That means that we've recently been successful running all of the UT's (which include creating a new repo) using the same environment as yours.

I've kicked off a [new run on master](https://dev.azure.com/ms/PowerShellForGitHub/_build/results?buildId=117723&view=results) to see if something has changed on the GitHub end since Saturday (when that last build ran).

To narrow things down, does this same error occur if you try doing a read-only action?

```powershell
Get-GitHubUser -Current
Get-GitHubRepository
```

I'm curious if the error that they've returned (about the user-agent) is a red herring and there's actually something else that's going on....

**Comment by alfred-madl** [comment]
PS /Users/alfredmadl> Get-GitHubRepository
Telemetry is currently enabled.  It can be disabled by calling "Set-GitHubConfiguration -DisableTelemetry". Refer to USAGE.md#telemetry for more information. Stop seeing this message in the future by calling "Set-GitHubConfiguration -SuppressTelemetryReminder".
Invoke-WebRequest: /usr/local/share/powershell/Modules/PowerShellForGitHub/0.15.1/GitHubCore.ps1:294
Line |
 294 |          $result = Invoke-WebRequest @params
     |                    ~~~~~~~~~~~~~~~~~~~~~~~~~
     |  Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other
     | possible causes.

PS /Users/alfredmadl>

**Comment by HowardWolosky** [comment]
Let's try this to further narrow down the problem.

```powershell
Clear-GitHubAuthentication
Get-GitHubRepository -OwnerName microsoft -RepositoryName PowerShellForGitHub
```

Let's see if there's any chance that this is related to your auth token by acting as an anonymous client.

**Comment by alfred-madl** [comment]
You won't believe it...OS reboot...all problems gone...so strange...

Sorry for bothering you.
