### ISSUE TITLE
New-GitHubPullRequest

### ISSUE THREAD

**Issue by felixfbecker** [microsoft/PowerShellForGitHub#30]
The absolute most important cmdlet for me.
Inspiration in `hub pull-request create` - will default to the current branch, figure out the repo from the current remote, prefill the message with the last commit message...

**Comment by TylerLeonhardt** [comment]
Came to this repo looking for this functionality! It would be great to see.

**Comment by rjmholt** [comment]
Hi, I recently wrote a small function in PowerShell to do this ([here](https://github.com/PowerShell/vscode-powershell/blob/a7401961967f50f0de0dc64a82718b1ceb9d8ec5/tools/GitHubTools.psm1#L174-L230)).

I'm sure it's far from being of the quality required from this repo, but would be interested in working with the maintainers to polish it up if they'd like.

**Comment by HowardWolosky** [comment]
Go for it.  The existing methods should provide a good template for what we're looking for with new functions to the module.  Given you're already familiar with the specific of the API in question, it should be fairly trivial to implement that within this module.
