### ISSUE TITLE
How can I get lastest commit which being merged (or not) from repository

### ISSUE THREAD

**Issue by natilux2** [microsoft/PowerShellForGitHub#303]
How can I get the latest commit which being merged (or not) from the repository

**Comment by HowardWolosky** [comment]
Hi @natilux2 -- I don't quite follow your question.  Can you try restating it differently? For a commit to be in a repo, it would have had to be merged.

In general, to interact with commits, you'll need to use the [Commits API's](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#commits).  Those have not yet been implemented in this module, but they are still accessible with a minimal amount of effort by using `Invoke-GHRestMethod` and providing the relevant input for the specific API.

For example, if you wanted to [list the top commits](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-commits) for this project, you could run:

```PowerShell
Invoke-GHRestMethod -UriFragment '/repos/microsoft/PowerShellForGitHub/commits' -Method Get
```
