### ISSUE TITLE
New-GitHubRepositoryFromTemplate

### ISSUE THREAD

**Issue by moretti-zenfolio** [microsoft/PowerShellForGitHub#308]
In the file USAGE.md line 622 you ahve this example:

` New-GitHubRepositoryFromTemplate -OwnerName MyOrg  -RepositoryName MyNewRepo-TemplateOwnerName MyOrg -TemplateRepositoryName MyTemplateRepo
`
But I have the folowing error: 
`New-GitHubRepositoryFromTemplate : A parameter cannot be found that matches parameter name 'TemplateRepositoryName'.`

What is the parameter to generate a repo from a template? I need to create from a private repository

**Comment by HowardWolosky** [comment]
Hi @moretti-zenfolio,

From the [Wiki documentation](https://github.com/microsoft/PowerShellForGitHub/wiki/New-GitHubRepositoryFromTemplate) (which you can also see from doing `Get-Help New-GitHubRepositoryFromTemplate -ShowWindow`), it looks like the syntax should be:

```powershell
New-GitHubRepositoryFromTemplate -OwnerName MyOrg -RepositoryName MyTemplateRepo -TargetRepositoryName MyNewRepo -TargetOwnerName Me
```

Looks like the example in USAGE.md never got updated as the syntax was refined during the initial pull request.  Thanks for pointing that out.  I'll get a fix posed to the documentation shortly.
