### ISSUE TITLE
Feature Request: Add The Ability to Create GitHub Repository Pattern Based Branch Protection Rules 

### ISSUE THREAD

**Issue by X-Guardian** [microsoft/PowerShellForGitHub#312]
#### Feature Idea Summary

The current `GitHubRepositoryBranchProtectionRule` functions do not allow the management of GitHub repository pattern based branch protection rules. e.g. a branch protection rule for all branches matching the `release/**/*` pattern. This is due to a limitation in the GitHub REST API in that the REST branch protection APIs do not support branch patterns.

The GitHub GraphQL [createbranchprotectionrule](https://docs.github.com/en/graphql/reference/mutations#createbranchprotectionrule) and [deletebranchprotectionrule](https://docs.github.com/en/graphql/reference/mutations#deletebranchprotectionrule) APIs do support branch patterns, so functions could be built to achieve this using these these GraphQL APIs.

#### Feature Idea Additional Details

Create the following additional functions that use the GraphQL API:

- `New-GitHubRepositoryBranchPatternProtectionRule`
- `Get-GitHubRepositoryBranchPatternProtectionRule`
- `Remove-GitHubRepositoryBranchPatternProtectionRule`

A new wrapper function `Invoke-GHGraphQL` would also need to be developed to call the GitHub GraphQL API.

#### Requested Assignment

- If possible, I would like to implement this.

**Comment by HowardWolosky** [comment]
@X-Guardian -- If you're willing to put the time and effort into writing it, I'll put in the time to review it.  I took a look at the [`branchprotectionrule`](https://docs.github.com/en/graphql/reference/objects#branchprotectionrule) object, and it's quite large.  That's definitely going to be a length parameter list...
