### ISSUE TITLE
Gists

### ISSUE THREAD

**Issue by dotps1** [microsoft/PowerShellForGitHub#32]
Just thought id throw this out there, but i have a pretty stable module out there that could be included in this for working with Gists:  https://github.com/dotps1/PSGist

i haven't updated it in a while, but defiantly could put some work into it if it where included in this repo.

thanks!

**Comment by raghav710** [comment]
@dotps1 was any work on this done?

**Comment by HowardWolosky** [comment]
It might be harder to directly integrate in given the difference in authentication behavior.
