### ISSUE TITLE
Set-GitHubConfiguration -ApiHostName validation not working

### ISSUE THREAD

**Issue by rmiroslavov** [microsoft/PowerShellForGitHub#332]
### Expected behavior:
`Set-GitHubConfiguration -ApiHostName "https://api.subdomain.domain.com"  `is getting validated and works

### Current behavior 
`Set-GitHubConfiguration -ApiHostName "https://api.subdomain.domain.com"  `is getting validated and works
throws 
```
Set-GitHubConfiguration : Cannot validate argument on parameter 'ApiHostName'. The argument "https://api.subdomain.domain.com" does not match the "^(?!https?:)(?!api\.)(?!www\.).*" pattern. 
Supply an argument that matches "^(?!https?:)(?!api\.)(?!www\.).*" and try the command again.
```

While `Set-GitHubConfiguration -ApiHostName "ttps://api.subdomain.domain.com"  ` is getting validated

testing on https://regex101.com/ confirm regex validation not working as intended

No match 
![image](https://user-images.githubusercontent.com/77494753/123952046-239d9980-d9ae-11eb-9822-bf730b33fd97.png)

Returns match 
![image](https://user-images.githubusercontent.com/77494753/123952104-36b06980-d9ae-11eb-804b-e8eb8b836e48.png)

###  Possible solution:
 on the regex validation, escape first "h" character

`^(?!\https:)(?!api\.)(?!www\.).*`

### Reproduced using:
```
$PSVersionTable

Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.19041.906                                                                                                                                                  
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.19041.906                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1                                                                                                                                                        

Windows 10
PowerShell ISE
```

**Comment by rmiroslavov** [comment]
Neverming, 
It works without prefixing "https://" or "api". 
Closing this.

**Comment by HowardWolosky** [comment]
Correct.  As documented:

https://github.com/microsoft/PowerShellForGitHub/blob/0ebf9e8b8d0f4fa361996674dbca804da36bace7/GitHubConfiguration.ps1#L69-L72

https://github.com/microsoft/PowerShellForGitHub/blob/0ebf9e8b8d0f4fa361996674dbca804da36bace7/GitHubConfiguration.ps1#L197-L201

Although maybe we need to consider just taking in whatever the input is and removing the part that we don't want, in order to be more user friendly....
