### ISSUE TITLE
New/Set-GitHubRepository: Add Support for `Allow Auto Merge` Option

### ISSUE THREAD

**Issue by X-Guardian** [microsoft/PowerShellForGitHub#357]
#### Feature Idea Summary

GitHub have added a new option 'Allow Auto Merge' to Repositories that could be added to the `New-GitHubRepository` and `Set-GitHubRepository` Cmdlets.

##### References:

- [Automatically Merging a Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request)

##### API Reference

- https://docs.github.com/en/rest/repos/repos#create-an-organization-repository
- https://docs.github.com/en/rest/repos/repos#update-a-repository

##### Parameters

- `allow_auto_merge`

#### Requested Assignment

- If possible, I would like to implement this.

**Comment by HowardWolosky** [comment]
Sounds good.  Thanks for bringing this up and coding the fix!
