### ISSUE TITLE
telemetry error

### ISSUE THREAD

**Issue by jambarnes-fi** [microsoft/PowerShellForGitHub#417]
#### Issue Details
WARNING: Encountered a problem while trying to record telemetry events.
This is non-fatal, but it would be helpful if you could report this problem
to the PowerShellForGitHub team for further investigation:

System.Management.Automation.RuntimeException: The remote server returned an error: (403) Forbidden.
403 | Component private link id does not match incoming link id and private endpoint connection has restricitve flags enabled
Items Received: 1
Items Accepted: 0
Errors:

index statusCode message
----- ---------- -------
    0        403 Component private link id does not match incoming link id and private endpoint connection has restricitve flags enabled

#### Steps to reproduce the issue
```powershell
   # Include your repro steps here

this may not be your issue.  I was trying to dump results of an API call to a text file and got the error.  not dumping to the text file does not produce the error however.

```

**Comment by HowardWolosky** [comment]
@jambarnes-fi - Thanks for the report.  Is this happening for you all the time, or did this just happen for you once?  I haven't seen that error before.

**Comment by jambarnes-fi** [comment]
It's been a little while since I was playing with it, but it was happening consistently.

**Comment by HowardWolosky** [comment]
Thanks for the report.  Given that we haven't heard any other reports of this, I'm going to assume for the timebeing that it was a side-effect of your specific usage.  @jambarnes-fi - If it does start popping up again, please either re-open this issue or create a new one.  Anything that you can do to provide steps that would allow me to reproduce the problem locally would greatly help the investigation.
